/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 16 17:19:47 2018. */

#include "mirabuiltin.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageHeader_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, MessageHeader, category, category, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MessageHeader, type, category, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageHeader, error, type, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
